### PR TITLE
OWL file addition & Proposed Manifest Changes

### PR DESCRIPTION
**Pull request by ThomasThelen**
## Whole Tale Ontology
This Pull request concerns itself with the addition of a Whole Tale Ontology and changes to the manifest file to accompany it.

### Version & Address
I'm proposing that the version is 1.0. This version of the ontology supports the concept of a Tale, Tale Versions, and describes relations to external data sets. In doing so, it fixes major issues with the manifest that prevent it from being a full 'linked data' document. Because it introduces the core concepts in a Tale, I think that a 1.0 suffices.

It will live at https://vocabularies.wholetale.org/wt/1.0/wt#Tale

I expect the overall structure to look like
```
vocabularies.wholetale.org/
   |-wt/
      |-1.0
        |-wt.ttl
      |-1.1
        |-wt.ttl 
   |-etc/
      |-1.0
        |-etc.ttl
      |-1.1
        |-etc.ttl 
```

### wt:Tale
The Tale object is defined to be a particular type of `schema:CreativeWork` and `ro:ResearchObject`.

As a `schema:CreativeWork`, the Tale can have the following properties that we're already using.
```
schema:author
schema:description
schema:identifier
schema:image
schema:name
schema:version
schema:hasPart
```
In doing so, we resolve the issue of using schema,org terms on an incorrect domain (ResearchObject) without having to make any changes to the way we parse the manifest in girder_wholetale.

By subclassing ResearchObject, we retain the original notion of RO/ORE:Aggregation to stay compatible with RO-Bundle/BagIt-RO.

#### Usage
This should be used as an `@type` for any object that conforms to the Tale definition. In our case, it's the root object in the manifest.

### wt:Version

This PR also introduces the notion of a Tale Version. It's defined to be a particular type of schema:CreativeWork. This lets us use schema properties such as `schema:name`, `schema:dateModified`, and `schema:creator`.

#### Usage

A Tale version is attached to a wt:Tale via [dc:hasVersion](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/hasVersion). The reasoning behind this is that `schema:version`, although valid for schema:CreativeWork and hence wt:Tale, has an expected value of a string or number _not_ a composite object. dc:hasVersion doesn't place any sort of expectation on what the value is.

### wt:usesDataset

This property is meant to be a replacement for the `Dataset` that is currently described in the manifest context.

#### Usage

This property should be used on `wt:Tale` objects to describe external data that was used.

### Use schema:keywords instead of schema:category

[schema:category](https://schema.org/category) should only be used on a few classes-none of which we're using. It's therefore invalid to use this property. The [schema:CreativeWork](https://schema.org/CreativeWork) has the [schema:keywords](https://schema.org/keywords) property, which aligns with what we mean by a Tale's 'category'.

### Add wt ontology to the context

We'll want to add the following to the manifest context

```
        {
            "wt": "https://vocabularies.wholetale.org/wt/1.0/wt#"
        }
```

### Replace 'Datasets' with 'wt:usesDataset`

The `Datasets` definition should be removed from the context. Then, its usage should be replaced with `wt:usesDataset`.

ie

```
    "Datasets": [
        {
            "@id": "urn:uuid:d3a3565e-64ed-4435-b4b9-ede416a99b8e",
            "@type": "schema:Dataset",
            "name": "Petermann Glacier Automated Weather Station",
            "identifier": "urn:uuid:d3a3565e-64ed-4435-b4b9-ede416a99b8e"
        }
    ], 
```

becomes

```
    "wt:usesDataset": [
        {
            "@id": "urn:uuid:d3a3565e-64ed-4435-b4b9-ede416a99b8e",
            "@type": "schema:Dataset",
            "schema:name": "Petermann Glacier Automated Weather Station",
            "schema:identifier": "urn:uuid:d3a3565e-64ed-4435-b4b9-ede416a99b8e"
        }
    ], 
```

### Prefix usesDataset members with schema

The `identifier`, `name`, and `type` should all be prefixed with `schema:`. See the example above for the correct change.

### Use schema:schemaVersion instead of schema:version
This is a minor point that there's a more accurate word, [schema:schemaVersion](https://schema.org/schemaVersion) for what we're trying to describe when we currently say that a Tale has schema:version 8.

`schema:version: 8` becomes `schema:schemaVersion: 8`

### Explicitly state the root object's type

It's not obvious that the root object is an ro:ResearchObject. With the current changes, it's also not obvious that it's a wt:Tale. We should add `"@type": "wt:Tale"`to the root object.

### CODE REVIEW

**Comment by tmcphillips** [comment]
This all looks good to me.  Great analysis.  

Would it be redundant to rename wt:Version to wt:TaleVersion?  (Obviously I've become a long-camel-cased-symbol guy from way too many years using Java.)  Seriously though, is there any danger of wt:Version being confused with the version of something else?  (E.g. the version of the Tale manifest schema?)

**Comment by ThomasThelen** [comment]
I don't see any issues with using TaleVersion, and I like the idea of camel cases for classes. If there aren't any shouts of frustration I'll go ahead and make that change.

After issuing this PR I went through some other parts of the manifest and filed an issue about a similar problem with how we're representing files on disk (see #3). This leads me to think that we should version it as 0.1 instead, and call it 1.0 when it's fully mature after fixing that issue and after any potential changes with the recorded run.

**Comment by craig-willis** [comment]
Thanks Tommy, this looks good.

Per my comment https://github.com/whole-tale/girder_wholetale/pull/441#pullrequestreview-582861130, do you think we should have our own `wt:identifier` or similar for our system UUIDs? 

Also, would you or @tmcphillips be willing to provide some sort of a test for this that includes loading into Blazegraph and confirming that things are what we say they are?  None of us noticed that the last version failed to parse...

**Comment by ThomasThelen** [comment]
I changed wt:Version to wt:TaleVersion; things seem to work just the same. I also added `queries.py` to the `examples/` directory. This file loads the manifest file with rdflib and performs SPARQL queries on the wt:TaleVersion object. The output is shown below, for [this](https://github.com/whole-tale/serialization-format/blob/065ac8719866f007ae05dd413695b2db5730e14d/examples/external-dataset/metadata/manifest.json) manifest.

I _think_ the issue with the file:// URI is that technically, an email address URI should start with `mailto:`, as per [rfc6068](https://tools.ietf.org/html/rfc6068).

```
Version ID: https://data.wholetale.org/api/v1/folder/4d082326cc895d0f7434f931
Version Name: My first Version
Last Modified: 2021-2-2
Creator ID: file:///Users/thomas/serialization-format/examples/external-dataset/metadata/thelen@nceas.ucsb.edu
Given Name: Thomas
Family Name: Thelen
Email Address: thelen@nceas.ucsb.edu
```

I can certainly add an example for loading into blazegraph if we want that, but it'll be a little less light weight than using rdflib. The rdflib stuff might be a good addition to the girder_wholetale tests and replaced here with blazegraph

**Comment by ThomasThelen** [comment]
As for creating our own wt:identifier, I'm pretty impartial. The schema,org `identifier property represents any kind of identifier`, so the interpretation is left as an exercise to the reader. We _can_ of course create our own if we want to give more context in the OWL definition. The only thing that tells me not to is that this is more of a `girder:identifier` and not necessarily related to Tales. In my mind the definition of a wt:identifier follows

> The identifier of an object that's specific to a Girder deployment.

**Comment by ThomasThelen** [comment]
I went ahead and created a `wt:internalIdentifier` property. It has domains `wt:Tale` and `ore:AggregatedResource`. The first, `wt:Tale`, is so that we can use it on the root Tale object. The second, `ore:AggregatedResource`, is so that we can use it on the aggregated objects. The range is a literal value, so we can just put a string there.

I also noticed an issue with the way graphs were using the DataCite namespace. Without a trailing slash, the properties were getting stuck to the end of the URL. This was a small enough change I added it here.

### Manifest Changes
1. The root `schema:identifier` should change to `wt:internalIdentifier`
2. The `schema:identifier` on aggregated objects should change to `wt:internalIdentifier`
3. Add the `mailto:` prefix for email URIs
4. Add a slash to the end of the DataCite namespace (http://datacite.org/schema/kernel-4/)


### Other Notes
The _last_ thing that I see preventing this from loading into Blazegraph is the contents of `folder` for bundled resources. This was briefly discussed [here](https://github.com/craig-willis/bdbag-water-tale/pull/1). Unfortunately, Blazegraph (and others) will hiccup while trying to parse a URI with spaces, hence the requirement for encoding it. rdflib is able to load it, but warns that 
> file:///Users/thomas/serialization-format/examples/external-dataset/data/data/Methane and nitrous oxide fluxes as a function of the timing of goose grazing Yukon Kuskokwim Delta Alaska 2016/ does not look like a valid URI, trying to serialize this will break.

Blazegraph will throw and exception when trying to read it
> java.util.concurrent.ExecutionException: org.openrdf.rio.RDFParseException: IRI included an unencoded space: '32' [line 40]


#### Other Nastiness
The other parts that should probably be changed are adding prefixes to the URIs. 

In the message above you'll see a long messy path relative to my computer. We should really be prefixing that URI with `file://`. Upon doing so you'll see the slightly more desirable warning
> file://../data/data/Methane and nitrous oxide fluxes as a function of the timing of goose grazing Yukon Kuskokwim Delta Alaska 2016/ does not look like a valid URI, trying to serialize this will break.

Along the same lines, we create an aggregation for the LICENSE file with a relative path `"uri": "../data/LICENSE"` which will result in a full path. 

##### Manifest fixes for other nastiesness
1. Add `file://` to `folder` objects 
2. urlencode `folder` objects
3. Add `file://` to the URI for the aggregated LICENSE file and other aggregated files
4. urlencode aggregated file URIs

**Comment by Xarthisius** [comment]
Can we use `arcp://` instead of `file://`? Following https://www.researchobject.org/ro-crate/1.1/appendix/relative-uris.html#establishing-a-base-uri-inside-a-zip-file

**Comment by Xarthisius** [comment]
While we're desperately trying to please the metadata gods can we also do the "right thing"^{TM}? Since we already added `wt:internalIdentifier`, `wt:Tale` etc. and the world didn't cease to exist, how about we add:
1. `wt:bagPath` showing *not encoded* path to a resource relative to the root of the bag (*without* any weird prefixes)
2. `wt:mountPath` describing where the resource is mounted relative to the Tale's `data/` directory, which is what we have in a live Tale.

### Example

Current entry:
```
{
    "uri": "https://cn.dataone.org/cn/v2/resolve/urn:uuid:01a53103-8db1-46b3-967c-b42acf69ae08",
    "schema:isPartOf": "doi:10.5065/D6862DM8",
    "bundledAs": {
        "folder": "../data/data/",
        "filename": "usco2005.xls"
    },
    "size": 6427136
}
```
would become:
```
{
    "uri": "https://cn.dataone.org/cn/v2/resolve/urn:uuid:01a53103-8db1-46b3-967c-b42acf69ae08",
    "schema:isPartOf": "doi:10.5065/D6862DM8",
    "bundledAs": {
        "folder": "file://../data/data/",
        "filename": "usco2005.xls"
    },
    "size": 6427136,
    "wt:bagPath": "/data/data/usco2005.xls",
    "wt:mountPath": "usco2005.xls"
}
```

**Comment by ThomasThelen** [comment]
> Can we use `arcp://` instead of `file://`? Following https://www.researchobject.org/ro-crate/1.1/appendix/relative-uris.html#establishing-a-base-uri-inside-a-zip-file

I'm not seeing the advantage of using the arcp root. In particular I see `RO-Crates may exist in a temporary file path which should not determine its identifiers.` as a strawman because of the files in the archive will _always_ be relative to the `metadata/manifes.json` file anyways (hence the `../`in the URIs). I might be missing something though.

If it's a pain/we can't do it already then I'd be fine adding `wt:bagPath` and `wt:mountPath`. At some point we might have to answer for it and if there's a way to do it without using our own terms I think the better.

**Comment by Xarthisius** [comment]
> because of the files in the archive will _always_ be relative to the `metadata/manifest.json` file anyways 

Where does that requirement come from? It would make much more sense to define all the files inside of the bag in terms of their path in the zipfile. In that sense they would be absolute and all that headache would go away.

**Comment by ThomasThelen** [comment]
> The aggregates section of the manifest list the payload files, both embedded (e.g. ../data/numbers.csv) and external resources (e.g. http://example.com/doc1). Note that local paths are under ../data/, relative to the metadata/ folder.

From [bagit-ro](https://github.com/ResearchObject/bagit-ro). RO-Bundle (where bagit-ro came from) would list the folder without the `../` and just a `/`. bagit-ro deviates from this, which is in the `Considerations` section

I also noticed that the folder isn't prepended with `file://` which is interesting because it seems that the graph stores are turning them into full paths. This can be seeing by pasting the [example manifest](https://github.com/ResearchObject/bagit-ro/blob/master/example1/metadata/manifest.json) into [this](https://www.easyrdf.org/converter) converter and viewing it as turtle; in this case a website URL is appended to the paths.

Edit: For completeness sake, when querying folder information without anything prepended it'll append the server address. In my case I get `<http://192.168.254.14:9999/blazegraph/namespace/kb/..%2Fdata%2Fdata%2FMethane%20and%20nitrous%20oxide%20fluxes%20as%20a%20function%20of%20the%20timing%20of%20goose%20grazing%20Yukon%20Kuskokwim%20Delta%20Alaska%202016%2F/>`

**Comment by ThomasThelen** [comment]
## Testing Instructions

### Running Blazegraph
1. Download [blazegraph.jar](https://github.com/blazegraph/database/releases/tag/BLAZEGRAPH_2_1_6_RC)
1. Run `java -server -Xmx4g -jar blazegraph.jar`
1. Navigate to the serviceUrl (should be in the blazegraph output)
1. Note that the database is stored in blazegraph.jnl. If you want a fresh database, delete this file between uses

### Loading the Manifest

1. Convert the manifest to turtle
   a. Open queries.py and replace the main method with the one [here](https://gist.github.com/ThomasThelen/03535dbc4eaeebeada597a344369ecd1). This will print the manifest as ttl
   b. Install rdflib & [rdflib-jsonld](https://github.com/RDFLib/rdflib-jsonld)
   c. Run the script
   d. Use [this](https://gist.github.com/ThomasThelen/c5590e1aec3d255591797b91d53e1f4e) ttl if you want to avoid doing the above.
1. Navigate to the blazegraph instance
1. Navigate to the `Update` tab
1. By the file selection button, select "RDF Data" under the "Type:" dropdown
1. Select "Turtle" as the format
1. Paste the turtle in the box & click 'Update'

### Showing the contents of the store
1. Navigate over to the "Query" tab
1.  Paste in and execute the following to see all of the triples
```
SELECT ?s ?p ?o
WHERE 
{
   ?s ?p ?o .
}
```

### Deviations
To see what things look like _without_ a `file://` prefix (but still encoded) use [this](https://gist.github.com/ThomasThelen/0a17f490c143abe403517f69115a8459) ttl, which is just the above without the file:// prefix.
Note that I couldn't find a way to get a clean db without deleting the journal file and restarting blazegraph. The alternative is to update the graph with the turtle, run the same select query, but look for new nodes. The difference should be that files now have your local URL appended to them (don't forget there's a page 2 of results)

To see what happens when things aren't urlencoded and don't have the prefix, use [this](https://gist.github.com/ThomasThelen/79cc180a95465cc6d49ae96db5399453) ttl. It should fail to load.

For more conformation, you can see how rdflib handles it by playing with the manifest.json file and printing the results out. You should see warnings about spaces in the file path and will also see full paths appended to the unprefixed terms. For another set of eyes you can see that https://www.easyrdf.org/converter does the same thing wile converting the json-ld to ttl

**Comment by craig-willis** [comment]
Per Slack discussions, the two ways I'm testing these changes are using Tim's https://github.com/CIRSS/geist environment with the Blazegraph CLI:
```
git clone https://github.com/CIRSS/geist
cd giest 
make pull-image
make run-image
...
blazegraph destroy --dataset kb
blazegraph create --dataset kb
blazegraph import --file <file> --format jsonld
```

And also `rdflib-jsonld` (adding `arcp` scheme support to urllib):
```
from rdflib import Graph

import urllib.parse
urllib.parse.uses_relative.append('arcp')
urllib.parse.uses_netloc.append('arcp')

g = Graph().parse(source="manifest.json", format="json-ld")
print(g.serialize(format='turtle', indent=2).decode())
```

Actual feedback to follow...

**Comment by craig-willis** [comment]
Summarizing a few points from discussions last week:
* The location of `metadata/manifest.json` is defined by the [bdbag-ro profile](https://raw.githubusercontent.com/fair-research/bdbag/master/profiles/bdbag-ro-profile.json). We can change this if needed by defining our own profile. However, since we can use @base (see below), it doesn't seem to matter much.
* We are the only ones using the "standard" and our primary requirements are export/publish/import, none of which uses LD/RDF features.  We should keep things clear/simple for our primary requirements. That said, ideally the tale metadata would parse as valid JSON-LD by the tools we use (blazegraph, rdflid) and produce sensible triples. 

My thoughts:
* We should introduce whatever changes help export/publish/import and not worry too much about standards conformance at this time. I don't think we should go crazy introducing unnecessary changes that increase complexity for our primary applications.
* Keep the current structure (metadata/manifest.json) unless it somehow simplifies things for our primary use cases. I'm open to moving the manifest and creating a new profile if it makes life easier.
* Use `@base` set to either the zip root  (`arcp://uuid,5xx/`,  `file:///`) or the payload (my preference -- `arcp://uuid,5xx/data/`,  `file:///data/`). Which scheme we choose doesn't matter. It will produce sensible triples while keeping things easy to parse. 
* Because of versioning, I think we should export tales based on the version UUID instead of tale UUID. This way exporting two versions would produce two different named zips.  If we use `arcp`, then we could use the version ID in the path (and possibly make the version the primary ID in the manifest -- open to discussion on this).
* Because the various paths are necessarily IRIs, we will need to urlencode the path elements (e.g., file/folder names), which we are not doing today. If we don't do this, then things like rdflib will fail to parse.
* Use `mailto:` for any email addresses to make them valid IRIs.
* Use consistent date formatting for date/time values (`dateModified` and `createdOn`)
* Change DataCite prefix to `dc` or `datacite` for consistency.

I've created an example with the above suggestions implemented (using arcp with payload directory as base):
* [revised-manifest.json](https://gist.github.com/craig-willis/35ac9b20419a779c4d656e5ee551d762)
* [revised-manifest.nt](https://gist.github.com/craig-willis/a097ac9444e97d24afdeb9a924613b5a)

**Comment by ThomasThelen** [comment]
Updates to the ontology.

### Rename Things
This was done to match the work done in the manifest refactor work

`internalIdentifier` is now just `identifier`. `usesDatasets` is now `usesDataset`

### File Terms
Created a few new terms for use when describing files. These are `wt:md5`, `wt:mimetype`, and `wt:size`

### Query Update
Explicitly added  arcp  to urllib so that the @base is properly respected while exporting

**Comment by ThomasThelen** [comment]
This should be okay to be reviewed now.
## Summary
A quick summary of the changes:

### Two New Classes

#### Tale
The Tale class is used as the class for the root of the manifest. It is both an ore:Aggregation _and_ a schema:CreativeWork, providing parity with the schema,org and ore terms used on it.

#### TaleVersion
The TaleVersion class holds properties about the Tale's version. It is a particular type of schema:CreativeWork, allowing us to use some schema,org properties for it


### Five New Properties

#### identifier
The identifier is used to describe identifiers that are specific to Whole Tale/girder. It is only useful to the Whole Tale system while reimporting Tales.

#### md5
The md5 relation is used to denote the md5 checksum of a file in the workspace.

#### mimetype
The mimetype relation describes the mimetype

#### size
The size describes the size, in bytes, of a file

### Version 1.0
These changes fix enough things to the point where it can be used with rdflib. For that reason we're calling it 1.0

### rdflib query examples
Added a two new examples: one with _just_ local data and another with multiple authors and that was published (note that we don't export published information to the manifest (from what I noticed))

**Pull request merged**
